### ISSUE TITLE
stop time missing in high-temperature calculation

### ISSUE THREAD

**Issue by gertingold** [michael-hartmann/caps#134]
While regenerating output examples, I just noticed that in the high-temperature calculation the start time is recorded in the output but not the stop time. May be the stop time should be added for consistency.

**Comment by gertingold** [comment]
By the way: ``capc`` and ``cass`` do not provide any timing information. In principle, this is acceptable as they do not have the same status as ``caps``.

**Comment by michael-hartmann** [comment]
Start and stop time are only present in `caps` because it is in general a long running MPI program.

I can add start and stoo time to the other programs as well if you think this is needed.

**Comment by gertingold** [comment]
Probably it is not necessary to print start and stop time for all programs. However, when a start time is printed it also makes sense to print the corresponding stop time. As far as I can tell, this concerns only ``caps`` with the ``--ht`` flag.

**Comment by gertingold** [comment]
Fixed in #136. The example output in the manual still needs to be updated accordingly.

**Comment by gertingold** [comment]
Example outputs have been updated in #140.
