### ISSUE TITLE
Build instructions: prefer 'build' over 'bin'

### ISSUE THREAD

**Issue by jwuttke** [michael-hartmann/caps#148]
In README.md, consider 'mkdir build' instead of 'mkdir bin'. Seems more standard to me.

**Comment by jwuttke** [comment]
<- https://github.com/openjournals/joss-reviews/issues/2011

**Comment by michael-hartmann** [comment]
You are right, `bin` is an uncommon name for the build directory. I have changed the readme file and the user manual to use `build` as build directory, see #154.
