### ISSUE TITLE
test_fresnel is excessively long

### ISSUE THREAD

**Issue by jwuttke** [michael-hartmann/caps#151]
slows down the entire compilation: what is the point in testing reproducibility for so many data points?

**Comment by jwuttke** [comment]
<- https://github.com/openjournals/joss-reviews/issues/2011

**Comment by michael-hartmann** [comment]
I agree that the number of test cases is too large and the compilation time is too long. I have drastically reduced the number of tests, but still testing the most common parameters and the most extreme parameters. See #155.
