### ISSUE TITLE
document where automatically generated source code comes from

### ISSUE THREAD

**Issue by jwuttke** [michael-hartmann/caps#152]
The files test_*.c look as if they have been automatically generated.

A short note in the header of each test source code should indicate how the code has been generated. It would be nice if tools used for this purpose were also released.

**Comment by jwuttke** [comment]
<- https://github.com/openjournals/joss-reviews/issues/2011

**Comment by michael-hartmann** [comment]
Following your suggestion I have cleaned up the tests a bit. I have added comment to the source file describing if they were generated by a script or how the reference data was obtained.

Some test files were partly generated by script. In some cases the respective Python script was not able to provide results or returned wrong results. In that cases, the reference values have been obtained using Mathematica. Unfortunately, this means that not all C test files can automatically generated by scripts.

See PR #158 for more details.
