### ISSUE TITLE
Add remark to JOSS paper

### ISSUE THREAD

**Issue by michael-hartmann** [michael-hartmann/caps#159]
Briefly mention in the JOSS paper that CaPS is currently the only openly available tool to compute the Casimir energy in the plane-sphere geometry.

openjournals/joss-reviews#2011

**Comment by gertingold** [comment]
There is also `MEEP` (https://meep.readthedocs.io/en/latest/) able to do Casimir calculations. Certainly, `MEEP` and `caps` have different domains of application. `MEEP` is more general purpose but not able to cover the aspect ratios handled by `caps`. The approach used by `MEEP` is also entirely different.

**Comment by gertingold** [comment]
... and there is also `SCUFF-EM` (http://homerreid.github.io/scuff-em-documentation/).

**Comment by michael-hartmann** [comment]
You are right. I didn‘t think of them because the focus is somewhat different. But I think we should  briefly mention them in the JOSS paper.
